Vagrant.configure(2) do |config|
  config.vm.box = "ierturk/alpine-3.14"
  config.vm.box_version = "0.1.0"
  config.vm.hostname = "alpine.int"
  config.vm.define "alpine-3.14"
  config.vm.provider "virtualbox" do |v|
    # v.name="alpine-3.14"
    v.memory = 1024
    v.cpus = 1
  end

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  config.vm.network "forwarded_port", guest: 22, host: 2244, auto_correct: false, id: "ssh"
end
