Vagrant.configure(2) do |config|
  config.vm.box = "opensuse/Tumbleweed.x86_64"
  config.vm.box_version = "1.0.20210726"
  config.vm.hostname = "os-tw.int"
  config.vm.define "os-tw"
  config.vm.provider "virtualbox" do |v|
    # v.name="alpine-3.14"
    v.memory = 1024
    v.cpus = 1
  end

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  config.vm.network "forwarded_port", guest: 22, host: 2224, auto_correct: false, id: "ssh"
end
